[package]
name = "jwt-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1" # For CORS
actix-web = "4.12.1" # For actix-web
bcrypt = "0.17.1" #For encrypting of password
chrono = { version = "0.4.42", features = ["serde"] } # For date and time, serde feature to enable serde
dotenvy = "0.15.7" # For use of .env file
env_logger = "0.11.8"
jsonwebtoken = { version = "10.2.0", features = ["rust_crypto"] } # For json web tokens
log = "0.4.29"
rand = "0.9.2" # For generating random values
serde = { version = "1.0.228", features = ["derive"] } # For serialization/deserialization
sqlx = { version = "0.8.6", features = ["chrono", "postgres", "runtime-tokio", "tls-rustls"] } # For db (chrono feature here is to enable chrono)
validator = { version = "0.20.0", features = ["derive"] } # For struct field validation


[[bin]]
name = "jwt-auth"
path = "src/main.rs"  # This tells Cargo to use `src/main.rs` as the entry point
